import Head from 'next/head'

import Seccion1 from '../Components/PagesComponents/Home/Seccion1'
import Seccion2 from '../Components/PagesComponents/Home/Seccion2'
import Seccion3 from '../Components/PagesComponents/Home/Seccion3'
import Seccion4 from '../Components/PagesComponents/Home/Seccion4'
import Seccion5 from '../Components/PagesComponents/Home/Seccion5'
import Seccion6 from '../Components/PagesComponents/Home/Seccion6'
import Seccion7 from '../Components/PagesComponents/Home/Seccion7'
import Seccion8 from '../Components/PagesComponents/Home/Seccion8'

import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>La bola blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <Seccion1 styles={styles} />
        <Seccion2 styles={styles} />
        <Seccion3 styles={styles} />
        <Seccion4 styles={styles} />
        <Seccion5 styles={styles} />
        <Seccion6 styles={styles} />
        <Seccion7 styles={styles} />
        <Seccion8 styles={styles} />
      </main>
    </div>
  )
}
